### ISSUE TITLE
Repo link broken  =)

### ISSUE THREAD

**Issue by metaleap** [dhruvrajvanshi/dhruvrajvanshi#1]
Link to Hades repo currently 404s.

While I have your attention — I ran into a curious mis-type-inference following your very fine 2018 type-inference series. Done part 1 so far. Generally works real neat but here's an odd lack of type-mismatch error, check this out in my bare-bones IR lang:

```
@fn [ z, x, y ] [
  strCharAt (strRange z x y) z,
]
```

As you'll have intuited from the names, `strCharAt` is pre-typed as `Str -> Uint -> Char` and `strRange` is pre-typed as `Str -> Uint -> Uint -> Str`.

This means `z` is used in conflicting places, first as a supposed-to-be-`Str` arg and second as a supposed-to-be-`Uint` arg.

Type inference decides `z` is `Uint` and leaves it at that, no err for the `strRange` arg use of `z`.

Now I guess it's because in your article everything is based on funcs having one param only. I have adapted things so that I do the stuff for multiple params/args that you do for just one, and then `composeSubstitution` them all together. I might have adapted this all wrong thusly. Any suggestions how to _properly_ handle multiple args/params? Danke  =)

**Comment by dhruvrajvanshi** [comment]
> Link to Hades repo currently 404s.

Danke dir! I've fixed it.

Now, onto your question.

> Type inference decides z is Uint and leaves it at that, no err for the strRange arg use of z.

Seems like a bug with or without multi param lambdas. I wrote it a long time ago :)

> I have adapted things so that I do the stuff for multiple params/args that you do for just one, and then composeSubstitution them all together.

It's possible that you've forgotten to pass the substitution returned when unifying the 1st argument to `infer(second arg)`,
or the third one.

It's also possible that you've forgotten to apply the substitution returned by `infer(strRange z x y)` to `unify(z.type, UInt)`. This would mean that unify will try to unify `z.type` to a new value, even though it's already typed.

It's of course possible that there's a bug in the original code (there were a few edits ad the end of Part 1 related to missing substitution passing).

Well I'm not sure where the bug is but the following is an explanation of how it's **supposed** to work.

```rust
fn [x, y, z] 
// we start the scope with an env with 3 variables, x, y and z with unknown types (let's call them ?1, ?2, ?3) + globals
// The only difference with the tutorial is that you extend the environment with 3 variables instead of 1, because your
// language has functions with multiple params
env = {
  z: ?1,
  x: ?2,
  y: ?3
  strCharAt: Str -> Uint -> UInt -> Char
  strRange: Str -> UInt -> UInt -> Str
}

infer(strCharAt (strRange z x y) z)
  infer(strCharAt) // straightforward because you can look up its type in the env (returns empty subst)
  infer(strRange z x y) // This will yield the type Char and a substitution, hopefully containing actual types for ?1, ?2, ?3
    // infer each term (strRange, z, x, y), then unify the inferred types of arguments with the expected types
    infer(strRange) -> Same as above, look up the value in the env (returns empty subst)
    infer(z) -> Env lookup, returns ?1
    unify ?1 with Str -> Returns the substitution s1 = { ?1 = Str }
    // also pass in the previous substitution here; Not used but still, use the latest substitution for all infer calls
    infer(x, s1) -> Env lookup, returns ?2
    unify ?2 and UInt -> Returns the substitution s2 = { ?2 = UInt }
    infer(y, compose(s1, s2)) -> s3 = { ?3 = UInt } // again, pass in the previous substitutions using composition
    unify ?3 and UInt -> s3 = { ?3 = UInt }
  // now we're done with infer(strRange z x y)
  // we know it returns a Str and a substitution
  compose({ ?1 = Str, ?2 = UInt, ?3 = UInt })
  // we can proceed with the inference of the outer expression
  // ... intermediate steps, omitting for clarity
  infer(z, compose(s1, s2, s3)) -> env lookup -> ?1
  unify ?1 and UInt -- THIS STEP WILL FAIL because ?1 is already instantiated to `Str`, which doesn't match UInt
    
```
The only difference from my tutorial is
1. At each function header, you'd extend the environment with multiple variables instead of just 1 (3 in your example).
2. When infering call expressions, you'd check all arguments with the expected types instead of just 1
         ``` 
              foo bar baz bat
              // guess foo to ?1 -> ?2 -> ?3 -> ?4
              // infer bar and unify the result with ?1
              // infer baz and unify the result with ?2 keep the previous substitution
     
         ```
I hope this makes sense.

**Comment by metaleap** [comment]
That helped greatly, merci!  =)
